#!/bin/sh

set -e

_MIRROR_SITE="http://mirrors.aliyun.com/debian/"
_MIRROR_SECURITY="http://mirrors.aliyun.com/debian-security/"

case "$(dpkg --print-architecture)" in
	amd64)
		_LINUX_FLAVOURS="amd64"
		_SOURCE="false"
		;;

	i386)
		_LINUX_FLAVOURS="686-pae"
		_SOURCE="false"
		;;
esac

lb config noauto \
	--clean \
	--ignore-system-defaults \
	--mode debian \
	--linux-flavours "${_LINUX_FLAVOURS}" \
	--linux-packages "linux-image linux-headers" \
	--bootappend-live "boot=live config locales=zh_CN.UTF-8 username=tony user-fullname=tony hostname=tonybox timezone=Asia/Shanghai" \
	--bootappend-live-failsafe "boot=live config quiet  locales=zh_CN.UTF-8 username=tony hostname=tonybox" \
	--archive-areas "main contrib non-free non-free-firmware" \
        --parent-mirror-bootstrap "${_MIRROR_SITE}" \
        --parent-mirror-chroot "${_MIRROR_SITE}" \
        --parent-mirror-binary "${_MIRROR_SITE}" \
        --parent-mirror-debian-installer "${_MIRROR_SITE}" \
        --mirror-bootstrap "${_MIRROR_SITE}" \
        --mirror-chroot "${_MIRROR_SITE}" \
        --mirror-binary "${_MIRROR_SITE}" \
        --mirror-debian-installer "${_MIRROR_SITE}" \
        --mirror-bootstrap "${_MIRROR_SITE}" \
		--mirror-binary-security "${_MIRROR_SECURITY}" \
		--mirror-chroot-security "${_MIRROR_SECURITY}" \
	--source "${_SOURCE}" \
	--iso-volume "NiixLinux" \
	--iso-publisher "Niix Linux Systems; etony.an@gmail.com" \
	--iso-application "NiixLinux" \
	--iso-preparer "NiixBuilder" \
	--bootloader syslinux \
	--distribution sid \
	"${@}"
	
##	--debian-installer live \ #DebianInstaller通常用于安装stable版，如需sid版，通常通过更改 /etc/apt/sources.list 后升级到sid版
##	--debian-installer-distribution bookworm \	
### 	--debian-installer netinst|live \ 仅适用于stable发行版
###	--apt-recommends false ##无法安装第三方软件
###--apt-indices false \ ####Unable to locate package squashfs-tools
